export { default as FirstSlide } from "./FirstSlide/FirstSlide"
export { default as SecondSlide } from "./SecondSlide/SecondSlide"
export { default as ThirdSlide } from "./ThirdSlide/ThirdSlide"
export { default as FourthSlide } from "./FourthSlide/FourthSlide"
export { default as FifthSlide } from "./FifthSlide/FifthSlide"
export { default as Navigation } from "./Navigation/Navigation"
export { default as Background } from "./Background/Background"